
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RCONJUNTO = 9;
  public static final int CONCATENACION = 3;
  public static final int DOSPUNTOS = 15;
  public static final int CONJUNTOGUION = 12;
  public static final int LETRA = 17;
  public static final int FLECHAASIGNAR = 16;
  public static final int LLAVEABRIR = 10;
  public static final int ID = 21;
  public static final int CUNILINEA = 20;
  public static final int CMULTILINEA = 19;
  public static final int CONJUNTOCOMA = 13;
  public static final int EOF = 0;
  public static final int DIGITO = 18;
  public static final int UNAMASVECES = 6;
  public static final int DISYUNCION = 4;
  public static final int CEROUNAVEZ = 7;
  public static final int error = 1;
  public static final int ESPECIAL = 8;
  public static final int PUNTOCOMA = 14;
  public static final int CEROMASVECES = 5;
  public static final int LLAVECERRAR = 11;
  public static final int PORCENTAJES = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PORCENTAJES",
  "CONCATENACION",
  "DISYUNCION",
  "CEROMASVECES",
  "UNAMASVECES",
  "CEROUNAVEZ",
  "ESPECIAL",
  "RCONJUNTO",
  "LLAVEABRIR",
  "LLAVECERRAR",
  "CONJUNTOGUION",
  "CONJUNTOCOMA",
  "PUNTOCOMA",
  "DOSPUNTOS",
  "FLECHAASIGNAR",
  "LETRA",
  "DIGITO",
  "CMULTILINEA",
  "CUNILINEA",
  "ID"
  };
}

